name: poincare
channels:
- anaconda
- pytorch
- defaults
dependencies:
- pip
- python=3.8
- nltk
- scikit-learn
- pytorch=1.9.0
- pandas
- h5py
- cython
- tqdm
- pip:
  - iopath
  - git+https://github.com/facebookresearch/hypernymysuite.git
